newrelic/newrelic-ios-agent

Agent/Instrumentation/NSURLSession/NRMAURLSessionOverride.m
Agent/Instrumentation/NSURLSession/NRMAURLSessionTaskOverride.m

In several instances, Distributed Tracing headers were not added to requests before they were sent off. This was due to not calling the proper method which would, simultaneously generate the DT headers, and add them to the request. Later, the Distributed Tracing Payload would be associated with the request, allowing for round trip tracing. In addition, DT headers were not being added to Swift Async requests before they went off, due to the delegate method setState not giving us a proper updated state in the newState parameter.

NR-234826 - Missing DT Headers

---

Agent/HandledException/NRMAHexUploader.m
Agent/Harvester/NRMAHarvesterConnection.m
Agent/Network/NRMANetworkFacade.mm

A crash was found when the allHeaders selector was sent to an instance of NSURLSession that was not also an NSHTTPURLSession, and this cast was not checked.

NR-239832 - Fix incorrect NSURLSession cast

---

Agent/Analytics/NRMAAnalytics.h
Agent/Analytics/NRMAAnalytics.mm
Agent/UserAction/NRMAUserActionFacade.mm
Tests/Unit-Tests/NewRelicAgentTests/Analytics-Tests/NRMAAnalyticsTest.mm
libMobileAgent/src/Analytics/include/Analytics/AnalyticsController.hpp
libMobileAgent/src/Analytics/include/Analytics/Constants.hpp
libMobileAgent/src/Analytics/src/AnalyticsController.cxx
libMobileAgent/src/Analytics/src/Constants.cxx

The offline attribute was only added to the new event system. This pr adds the attribute to the old event system. An event should have the offline attribute when it is created while the device is in an offline state.

Added the offline attribute to the old event system

---

Agent/Harvester/DataStore/NRMAAgentConfiguration.h
Agent/Harvester/DataStore/NRMAAgentConfiguration.m
Agent/Public/NewRelic.h
Agent/Public/NewRelic.m

There was a typo in offline storage configuration, megaBytes instead of megabytes.

Fixed a typo in our offline configuration functions

---

dsym-upload-tools/README_RUN_SYMBOL_TOOL.MD
dsym-upload-tools/run-symbol-tool.swift
examples/manual/FrameworkExample/dsym-upload-tools/README_RUN_SYMBOL_TOOL.MD
examples/manual/FrameworkExample/dsym-upload-tools/run-symbol-tool.swift
examples/spm/SPMExample/SPMExample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

https://new-relic.atlassian.net/browse/NR-231192 
Here is an example of the full curl from changes:
```
Executing $ curl --retry 3 --write-out %{http_code} --silent --output /dev/null -F upload=@"/Users/cdillard/Library/Caches/B785AEAD-D903-49A8-AAF3-4DB773885556/mapArchive.zip" -H "x-app-license-key: APP-TOKEN-NRMA" -H "X-NewRelic-Agent-Version: 7.4.10" -H "X-NewRelic-OS-Name: iOS" -H "X-NewRelic-Platform: Native" -H "X-NewRelic-App-Version: 1.2.3" -H "X-File-Size: 34193" https://mobile-symbol-upload.newrelic.com/map
```
Notice the new curl format we now will support a couple things:
We previously supported changing the host name via setting the env var  prior to the run-symbol-tool line:
eg:
export DSYM_UPLOAD_URL="https://staging-mobile-symbol-upload.newrelic.com"
Now we additionally …

NR-231192: run-symbol-tool updates for DEM

---

Agent/Public/NewRelic.h
Agent/Public/NewRelic.m
Tests/Unit-Tests/NewRelicAgentTests/API-Tests/NewRelicTests.m

For use in hybrid agents, added an additional static method to retrieve additional tracked headers added to requests.

Feature/NR-189606: Retrieve Static HTTP Headers

---

Agent/DistributedTracing/W3CTraceState.h
Agent/DistributedTracing/W3CTraceState.mm
Tests/Unit-Tests/NewRelicAgentTests/DistributedTesting-Tests/TestW3CTraceState.mm

The New Relic iOS agent used to send traceState header of the form:
`1@nr=0-2-10816994-25789457-17172750e6ff8549--0--1609970157093`
Where we have the following format:
```
[W3CTraceState trustedAccountKeyFor: traceContext], // 1
[W3CTraceState getVersion],                         // 2
[W3CTraceState getParentType],                      // 3
traceContext.accountId,                             // 4
traceContext.appId,                                 // 5
traceContext.spanId,                                // 6
traceContext.TRACE_FIELD_UNUSED,                    // 7
// Note: We used to pass 0 as the sampled flag but the Language agent teams requested this change.
//                              [W3CTraceState getSampled],                         // 8
[W3CTraceState getPriority], …
```

NR-256157: Remove Sample flag from traceState header for dist tracing

---

Agent/Analytics/Events/NRMAMobileEvent.m
Agent/Analytics/NRMAAnalytics.mm
Agent/General/NewRelicAgentInternal.h
Agent/General/NewRelicAgentInternal.m
Agent/Harvester/NRMAHarvester.mm
Agent/Utilities/NewRelicInternalUtils.m
fastlane/BuildFastfile

The APIs that background relies on are not available for watchOS. For now I macro'd around it to get it to build. More research needed to include it.

WatchOS background exclude

---

Agent.xcodeproj/project.pbxproj
Agent.xcodeproj/xcshareddata/xcschemes/Agent-watchOS.xcscheme
Agent.xcworkspace/contents.xcworkspacedata
Tests/Agent-watchOS.xctestplan
Tests/Unit-Tests/NewRelicAgentTests/API-Tests/APINetworkNoticeTest.m
Tests/Unit-Tests/NewRelicAgentTests/NSURLSession-Tests/NRMAURLSessionHeaderTrackingTests.m
Tests/Unit-Tests/NewRelicAgentTests/NSURLSession-Tests/NRMAURLSessionHeaderTrackingTestsOldEventSystem.m
Tests/Unit-Tests/NewRelicAgentTests/Uncategorized/NRMAUDIDManagerTest.m
Tests/Unit-Tests/NewRelicAgentTests/Uncategorized/NRNSURLConnectionSupportTests.m
Tests/Unit-Tests/NewRelicAgentTests/Uncategorized/NRReachabilityTest.m
fastlane/README.md
fastlane/TestFastfile

Adds a test target for the WatchOS agent. Due to limitations of WatchOS, some tests were omitted, and some tests were modified to better suit WatchOS.

Added Test Target to watchOS

---

Agent/General/NewRelicAgentInternal.m

I was able to figure out how to get watchOS to listen to the notifications for WKApplicationWillEnterForegroundNotification and WKApplicationDidEnterBackgroundNotification.

Added notifications to NewRelicAgentInternal for watchOS

---

Agent/Utilities/NRMAUDIDManager.m
Test Harness/NRTestApp/NRTestApp/AppDelegate.swift
Test Harness/NRTestApp/NRTestApp/Helpers/NewRelic+Replace.h

https://new-relic.atlassian.net/browse/NR-266202 
**Description**
Hero request received related to code in the new relic agent related to cryptography
> Hi hero, Capital One shared this:“We recently have received a new security finding from our DAST tool Data Theorem that the New Relic iOS agent is in violation for Hash Generated Using Broken Cryptography API (SHA1) due to the vulnerable code locations use the CC_SHA1 or CryptoKit.Insecure.SHA1 hashing functions, which leverage hashing algorithms that are proven to be vulnerable to collision attacks, and are unsuitable for modern use..Looking at the open source Agent this looks to be in NRMAUDIDManager for secureUDIDStore, getUDID & setUDID.
Would it be possible to look to get an update when these are updated to use SHA512 instead of …

[iOS] NR-266202: Adjust CryptoKit sha1 -> sha1256

---

Agent/Analytics/NRMAAnalytics.mm

On WatchOS, potentially due to having less memory, the NSDate object pointed to by _sessionStartTime becomes deallocated during a run. As this file does not use ARC, explicit retain/release calls need to be added to ensure the object is held on to.

NR-264174 - Retain/Release for _sessionStartTime

---

Agent/Analytics/Events/NRMAMobileEvent.h
Agent/Analytics/NRMAAnalyticEventProtocol.h
Agent/Analytics/NRMAPayload.h

This PR replaces the New Relic iOS agent usage of NSCoding with NSSecureCoding.
More information in JIRA ticket here: https://new-relic.atlassian.net/browse/NR-261761
> Capital One has found that, in our open source agent, there are several instances where NSCoding is used instead of the more secure NSSecureCoding. The files indicated by them are NRMAAnalyticEventProtocol, NRMAMobileEvent, and NRMAPayload. We should investigate whether these can be updated to use NSSecureCoding, and if possible, do so.

NR-261761: NSSecureCoding

---

Agent/General/NewRelicAgentInternal.m
Agent/Utilities/NewRelicInternalUtils.m
Tests/Unit-Tests/NewRelicAgentTests/Analytics-Tests/NRMAAnalyticsTest.mm

Instead of being hardcoded to "Landscape" like tvOS, watchOS now reports what wrist the device is on, whether the crown is on the left or right side of the device, and if the display has been autorotated. Autorotation would be the case if the user has flipped their wrist to show someone else the screen, for instance.

Feature/NR-270936 - watchOS Orientation Reporting

---

Agent/Analytics/NRMAAnalytics.h
Agent/Analytics/NRMAAnalytics.mm
Agent/General/NewRelicAgentInternal.h
Agent/General/NewRelicAgentInternal.m
Agent/Public/NewRelic.h
Agent/Public/NewRelic.m
Test Harness/NRTestApp/NRTestApp/ViewModels/UtilViewModel.swift
Tests/Unit-Tests/NewRelicAgentTests/API-Tests/NRMAAPIHelperTests.m
Tests/Unit-Tests/NewRelicAgentTests/API-Tests/NewRelicTests.m

https://new-relic.atlassian.net/browse/NR-270228 
This PR adds new session handling to the setUserId routine.
This accomplishes the following AC:
```
1. When setUserID(value: string|null) is called:
a. If userID was previously null and new value is non-null:
i. continue the current session and set the new userID
b. If userID was previously not-null and new value is different (including null):
i. end the current session and perform harvest
ii. start a new session with the new userID
```
There is challenges testing this change. There will be tests added at a later date.

NR-270228: New setUserId session handling.

---

Agent.xcodeproj/project.pbxproj
Agent/Analytics/Events/NRMAMobileEvent.m
Agent/Analytics/PersistentEventStore.m
Tests/Unit-Tests/NewRelicAgentTests/Analytics-Tests/PersistentStoreTests.m

This replaces our PersistentStore's current usage of unarchiveTopLevelObjectWithData with more secure NSKeyedUnarchiver decodeObjectOfClasses.
https://new-relic.atlassian.net/browse/NR-261761

NR-261761-2: Wrap up NSSecureCoding fixes, bump to iOS 11.0

---

Agent/General/NewRelicAgentInternal.m

Found a code path where background reporting was not being checked before shutting down the agent, leading to background events not being stored. Also discovered that there was not a way to harvest events before the new session started. Harvest now occurs on returning from background, if background reporting is enabled.

NR-277643 - Prevented shutdown for BG reporting

---

Agent/Analytics/Events/NRMAMobileEvent.m
Agent/Analytics/PersistentEventStore.m
Agent/General/NewRelicAgentInternal.m
Agent/HandledException/NRMAHandledExceptions.mm
Tests/Unit-Tests/NewRelicAgentTests/Analytics-Tests/PersistentStoreTests.m

This PR corrects the NewRelicAgentInternal start class to create requisite folders on launch, regardless of whether or not handled exceptions are enabled.
Missing from previous NSSecureCoding PR.  I think that [NSNumber class] is needed in MobileEvent as well , missed that in the NSSecureCoding PR

NR-283336: Fix missing attribs - call createDirectoryAtPath when hex disabled.

---

Agent/Analytics/NRMAEventManager.m
Tests/Unit-Tests/NewRelicAgentTests/Analytics-Tests/NRMAAnalyticsTest.mm
libMobileAgent/src/Analytics/src/EventManager.cxx

This PR changes the maxQueueTime detection to account for the 1 min harvest cycle. This change allows events to be harvested within the maxBufferTime instead of the minute after when the harvest cycle ticks.
- Scenario 1: No events in the queue. 
Events will not be harvested
- Scenario 2: maxBufferTimeSeconds = 60 seconds. 
As long as an event exists it will be harvested every harvest cycle.(1 min)
- Scenario 3: maxBufferTimeSeconds = 600 seconds. 
Events will be sent when the oldest event is between 541-600 seconds old at the harvest cycle tick.

NR-160576 change to make sure the minimum time is respected.

---

Agent/Analytics/NRMAAnalytics.mm
Agent/HandledException/NRMAHandledExceptions.mm
Agent/Public/NRMAExceptionHandlerStartupManager.m

Hybrid agent - Flutter is experiencing a crash when calling recordHandledException. I wasn't able to reproduce it or create a test that reproduces it, but this code should protect us against passing nil to JSONObjectWithData.
add some protection places we use sessionAttributeJSONString + NSJSONSerialization JSONObjectWithData

Nr-296083: Fix up getSessionAttributesResultMap to nil check sess attribs

---

Agent/Analytics/NRMAAnalytics.h
Agent/Analytics/NRMAAnalytics.mm
Tests/Unit-Tests/NewRelicAgentTests/Analytics-Tests/NRMASAMTest.mm

Added the prefix list to use in the new event system attribute validator.

NR-317126 New Event System session attribute can't contain a reservedAttributeNames

---

Agent/General/NewRelicAgentInternal.m

Changed the #if so that NSProcessInfo is used for watchOS and not for iOS/tvOS

NR-308480 fixed the double mobileSession

---

Agent/Public/NRLogger.h
Agent/Utilities/NRLogger.m
Tests/Unit-Tests/NewRelicAgentTests/Uncategorized/NRLoggerTests.m

fix the log:inFile methods to check for remote log level.
Fix addLogMessage to check local log level before emitting to Console and Remote Log Level before emitting to file.

NR-335442: NRLogger: fix the log:inFile methods to check for remote log level.

---

.github/workflows/main.yml
Agent.xcodeproj/project.pbxproj
Agent/FeatureFlags/NRMAFlags.h
Agent/FeatureFlags/NRMAFlags.m
Agent/General/NewRelicAgentInternal.m
Agent/Harvester/NRMAHarvester.mm
Agent/Public/NRLogger.h
Agent/Public/NewRelicFeatureFlags.h
Agent/Utilities/NRAutoLogCollector.h
Agent/Utilities/NRAutoLogCollector.m
Agent/Utilities/NRLogger.m
Test Harness/NRTestApp/NRTestApp/AppDelegate.swift
Test Harness/NRTestApp/NRTestApp/Helpers/triggerException.h
Test Harness/NRTestApp/NRTestApp/Helpers/triggerException.m
Test Harness/NRTestApp/NRTestApp/ViewModels/UtilViewModel.swift
Tests/Stress-Tests/Logging Stress Tests/NRAutoCollectLogStressTest.m
Tests/Unit-Tests/NewRelicAgentTests/Uncategorized/NRLoggerTests.m

https://new-relic.atlassian.net/browse/NR-318119

Nr 318119 auto collect stdout & stderr logs

---

Agent/Analytics/NRMAAnalytics.mm
Agent/Network/NRMANetworkFacade.mm
Test Harness/NRTestApp/NRTestApp/ViewModels/UtilViewModel.swift
Tests/Unit-Tests/NewRelicAgentTests/Analytics-Tests/NRMAAnalyticsTest.mm

https://new-relic.atlassian.net/browse/NR-334116
Update NRMANetworkFacade noticeNetworkRequest to work with passed params

NR-334116: allow http header tracking when using noticeNetworkRequest manually. Update NRMAAnalyticsTest

---

Agent/Utilities/NRLogger.m
Tests/Unit-Tests/NewRelicAgentTests/Uncategorized/NRLoggerTests.h
Tests/Unit-Tests/NewRelicAgentTests/Uncategorized/NRLoggerTests.m

https://new-relic.atlassian.net/browse/NR-348708 
The task  ensures that all mobile log events include session attributes and custom attributes added via the setAttribute method. This applies to logs generated through any static log method as well.

Nr 348708: add session attributes to log common attribute

---

Agent/Analytics/NRMASAM.mm
Tests/Unit-Tests/NewRelicAgentTests/Analytics-Tests/NRMASAMTest.mm

Changed NRMASAM to add the persisted attributes individually so that they get re-persisted which is closer to how the old event system does it in SessionAttributeManager::restorePersistentAttributes().
Now the session attributes should persist until removed like in the old event system.

NR-352010 Changed NRMASAM to add the persisted attributes individually so that they get re-persisted

---

Agent/Analytics/NRMAAnalytics.mm
Agent/Analytics/NRMAEventManager.m
Agent/Analytics/PersistentEventStore.m

Change it to use weak reference to prevent retain cycles and strong references to ensure the object is not deallocated while being used within the block.

NR-364636 fixing the persistent store memory leak

---

Agent/Instrumentation/NSURLSession/NRMAURLSessionOverride.m
Agent/Instrumentation/NSURLSession/NRMAURLSessionTaskOverride.h
Agent/Instrumentation/NSURLSession/NRMAURLSessionTaskOverride.m
Agent/Public/NRConstants.h
Test Harness/NRTestApp/NRTestApp/Helpers/ApodURL.swift
Test Harness/NRTestApp/NRTestApp/ViewControllers/ViewController.swift
Test Harness/NRTestApp/NRTestApp/ViewModels/ApodViewModel.swift

NR-363895; port setState swift async request changes from bespoke build to 7.5.x

---

Agent/Network/NRMAHTTPUtilities.mm

The startTrip method is now synchronized using @synchronized (self). This ensures that the method is thread-safe and prevents race conditions when multiple threads attempt to access or modify currentTraceId and currentParentId.
The currentTraceId and currentParentId variables are initialized to empty string at the beginning of the implementation. This ensures that they have a known state before being used.

NR-371375 changes to address startTrip crash

---

Agent/APrivateHeader.h
Agent/Analytics/Constants.h
Agent/Analytics/Constants.m
Agent/Analytics/NRMAAnalytics.mm
Agent/SessionReplay/SessionReplayManager.swift

Added hasReplay to session attributes when session replay is recording. We add the attribute when the timers for session replay start. We remove the attribute when a new session starts, it will be added again if the session replay starts again.

NR-415835 hasReplay attribute

---

Agent/CrashHandler/NRMAExceptionHandlerManager.m

This PR will clear the SessionReplayFrames document directory folder if the agent starts and there are no crashes to upload. This will effectively delete any stale data on device.

Session Replay fix: Clear persisted frames if no crashes to upload

---

.github/workflows/productionDeploy.yml

It seems like the macos-15 image now returns something that uses Xcode 26 or Xcode 16.4 and it auto updated to latest. this should use compatible version.

update: Use macos-14 on productionDeploy to prevent update issues

---

Agent/SessionReplay/NRMASessionReplay.swift

fix: move swizzle to start to only touch swizzle when enabled.
Checking if touch tracking still works after backgrounding and foregrounding with the various mechanisms MSR can start in like remotely.

fix: move swizzle to start to only touch swizzle when enabled

---

Agent/Harvester/NRMAHarvestController.m
Agent/Network/NRMAHTTPUtilities.mm

This PR changes error logs to debug level. These logs occurred when a network request happened while the agent was using the default harvester config. It also changes it so if there is a fetch-able harvest config, use that for harvester initialization. 
I can not find a reason to not just use the fetched config if it is available as early as possible. The mechanisms for requesting an updated config if there is an app / agent update or 409 CONFIGURATION_UPDATE still function.

NR-472539 changed the distributed tracing not attaching log to debug
